Conversions to and from python objects. Refs #167 #202 #156
APrioriInvestments/typed_python pull request #208
Opened 2019-08-08 02:51 UTC by rubidge

## Motivation and Context
Improve scope of compilation with ability to convert typed-python types to object.
Allow bytes literals.
Allow repr() and str() on typed python Classes.

## Approach
This uses the approach of passing a raw type pointer (Type*) to identify the type. (Not the getOrSetTypeResolver as mentioned in #167.)

## How Has This Been Tested?
Back and forth conversions produce same value.
Bytes literals are used in compiled functions.
repr() and str() work on typed python Classes with custom __repr__ or __str__.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2019-08-08 14:33 UTC, braxtonmckee requested changes

2019-08-08 14:33 UTC, braxtonmckee commented on typed_python/_runtime.cpp
> +        PyInstance::copyConstructFromPythonInstance((Type *)tp, (instance_ptr)&tgt, obj, true);
you need to be passing tgt, not `&tgt`.  Imagine Type is NamedTuple(x=int,y=int). This takes up 16 bytes. As it currently stands, you will take the NamedTuple out of the python object and jam it into the 16 bytes of stackspace that have been allotted for `tgt`, which is 8 bytes. 

This function ought to read

```
void np_runtime_pyobj_to_typed(PyObject* ob, instance_ptr tgt, Type* tp) {
    PyEnsureGilAcquired acquireTheGil;
    PyInstance::copyConstructFromPythonInstance(tp, tgt, obj, true);
}
```

Then, when you call it, just drop the 'store' operation.  Take the NamedTuple case. You're already passing it 'targetInstance.expr' , which is in fact a NamedTuple*. You cast it to void* to pass it to this function, and it comes in as 'tgt'.

2019-08-08 14:38 UTC, rubidge commented
Thanks, will make this change...

On Thu, Aug 8, 2019 at 10:33 AM Braxton McKee <notifications@github.com>
wrote:

> *@braxtonmckee* requested changes on this pull request.
> ------------------------------
>
> In typed_python/_runtime.cpp
> <https://github.com/APrioriInvestments/nativepython/pull/208#discussion_r312069360>
> :
>
> > @@ -303,20 +340,139 @@ extern "C" {
>          return floorresult;
>      }
>
> -    PyObject* nativepython_runtime_int_to_pyobj(int64_t i) {
> +    // returns layout*
> +    uint8_t *np_runtime_pyobj_to_typed(PyObject *obj, uint8_t* tgt, Type* tp) {
> +        // tgt is a layout pointer
> +        PyEnsureGilAcquired acquireTheGil;
> +        PyInstance::copyConstructFromPythonInstance((Type *)tp, (instance_ptr)&tgt, obj, true);
>
> you need to be passing tgt, not &tgt. Imagine Type is
> NamedTuple(x=int,y=int). This takes up 16 bytes. As it currently stands,
> you will take the NamedTuple out of the python object and jam it into the
> 16 bytes of stackspace that have been allotted for tgt, which is 8 bytes.
>
> This function ought to read
>
> void np_runtime_pyobj_to_typed(PyObject* ob, instance_ptr tgt, Type* tp) {
>     PyEnsureGilAcquired acquireTheGil;
>     PyInstance::copyConstructFromPythonInstance(tp, tgt, obj, true);
> }
>
> Then, when you call it, just drop the 'store' operation. Take the
> NamedTuple case. You're already passing it 'targetInstance.expr' , which is
> in fact a NamedTuple*. You cast it to void* to pass it to this function,
> and it comes in as 'tgt'.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/APrioriInvestments/nativepython/pull/208?email_source=notifications&email_token=ALOXRC32UNY67IRAV2I4UALQDQVC5A5CNFSM4IKF3KCKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCA74PAQ#pullrequestreview-272615298>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALOXRC6NRJBF4P3N66RDH5TQDQVC5ANCNFSM4IKF3KCA>
> .
>

2019-08-13 03:05 UTC, braxtonmckee commented on typed_python/_runtime.cpp
> +        PyInstance::copyConstructFromPythonInstance(tp, tgt, obj, true);
what happens if this conversion fails. Do we have tests for this case?

2019-08-14 01:42 UTC, merged