Provide conversions to bool for many types. Refs #210, #209, #212.
APrioriInvestments/typed_python pull request #218
Opened 2019-08-23 18:11 UTC by rubidge

## Motivation and Context
* Provide bool conversion functionality.

## Approach
* Conversions to bool for most types, interpreted and compiled.
    * including Classes with __bool__ or __len__ methods
    * including Alternatives with __bool__ or __len__ methods
* Conversions to bool for any object.
* When compiling, consistently check that expression is a reference before treating it as an instance pointer.
* Also fix some string conversions:
    * Avoid buffer overflow in nativepython_int64_to_string.
    * Provide suitable uint64 conversion to string.
* and some cosmetic changes

## How Has This Been Tested?
* Compare direct bool() with compiled bool and SpecializedEntrypoint
* Note there is a failing case (outer_specialized_bool) in python_obect_of_type_compilation_test.py that warrants further investigation.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2019-08-26 22:20 UTC, braxtonmckee requested changes
looks great - a couple of comments need to get dropped, and we need to dispatch to __bool__ from compiled code, not go through an interpreter call.

2019-08-26 22:20 UTC, braxtonmckee commented on nativepython/tests/python_object_of_type_compilation_test.py
> +            # r4 = outer_specialized_bool(x)
this is important. please file a ticket for this, ideally with a minimal repro test in the issue

2019-08-26 22:20 UTC, braxtonmckee commented on nativepython/type_wrappers/arithmetic_wrapper.py
> +        # elif target_type.typeRepresentation == String:
let's remove this.

2019-08-26 22:20 UTC, braxtonmckee commented on typed_python/_runtime.cpp
> +//        ReprAccumulator acc(s);
can we drop this comment?

2019-08-26 22:20 UTC, braxtonmckee commented on nativepython/type_wrappers/alternative_wrapper.py
> +                        runtime_functions.instance_to_bool.call(e.expr.cast(VoidPtr), tp)
why are we hitting a C function here? This will be very slow in a tight loop.  If the alternative has this method, we should be able to dispatch to it directly from compiled code. Similarly for Class objects.

2019-08-27 15:26 UTC, rubidge commented on nativepython/type_wrappers/alternative_wrapper.py
> +                        runtime_functions.instance_to_bool.call(e.expr.cast(VoidPtr), tp)
Ok, thanks, I'm looking into how to use call_py_function here.

2019-08-27 15:27 UTC, rubidge commented on nativepython/type_wrappers/arithmetic_wrapper.py
> +        # elif target_type.typeRepresentation == String:
Yes, I should have cleaned this up earlier.

2019-08-28 20:56 UTC, rubidge commented on nativepython/tests/python_object_of_type_compilation_test.py
> +            # r4 = outer_specialized_bool(x)
https://github.com/APrioriInvestments/nativepython/issues/219

2019-09-11 18:26 UTC, rubidge commented
Superseded by #225.

2019-09-11 18:26 UTC, closed without merging